# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test2.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0btest2.proto\"n\n\x08testinfo\x12\x0f\n\x07\x64\x65vtype\x18\x01 \x02(\x05\x12\r\n\x05\x64\x65vid\x18\x02 \x02(\x05\x12\x0e\n\x06unitid\x18\x03 \x02(\x05\x12\r\n\x05\x63hlid\x18\x04 \x02(\x05\x12\x11\n\x06testid\x18\x05 \x01(\x05:\x01\x30\x12\x10\n\x08stepdata\x18\x06 \x02(\x0c')
)




_TESTINFO = _descriptor.Descriptor(
  name='testinfo',
  full_name='testinfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devtype', full_name='testinfo.devtype', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='devid', full_name='testinfo.devid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unitid', full_name='testinfo.unitid', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chlid', full_name='testinfo.chlid', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testid', full_name='testinfo.testid', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stepdata', full_name='testinfo.stepdata', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['testinfo'] = _TESTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

testinfo = _reflection.GeneratedProtocolMessageType('testinfo', (_message.Message,), dict(
  DESCRIPTOR = _TESTINFO,
  __module__ = 'test2_pb2'
  # @@protoc_insertion_point(class_scope:testinfo)
  ))
_sym_db.RegisterMessage(testinfo)


# @@protoc_insertion_point(module_scope)
